appConfig:
  app-name: changcheng-wedding
  allow-cross-domain-access: true
  environment: dev   # 表示当先项目部署的环境,开发=dev,测试=test,线上=master
  domain: wedding.changcheng.site # 不同环境地址不同

logging:
  config: classpath:logback.xml

server:
  port: 8000
  session-timeout: 1800
#  ssl:
#    key-store: wx.pfx
#    key-store-password: slM308vh
#    keyStoreType: PKCS12
#    keyAlias: tomcat


spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    name: datasource
    url: jdbc:mysql://47.95.236.75:3306/wedding?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF8&autoReconnect=true
    username: root
    password: 12345678
    max-active: 2
    max-idle: 2
    min-idle: 2
    initial-size: 2
    validation-query: select 1
    test-on-borrow: true
    test-on-return: false
    test-while-idle: true
    time-between-eviction-runs-millis: 3000
    min-evictable-idle-time-millis: 3000
    max-wait: 3000
    jmx-enabled: true
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: site.changcheng.wedding.dao
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
session:
  expiration: 2592000                       #one month, unit: second
  validation-urls:
    include-patterns:
      - "/**"
    exclude-patterns:
      - "/"
      - "/error"
      - "/login"
      - "/swagger-ui.html"
      - "/configuration/**"
      - "/swagger-resources"
      - "/api-docs/**"
      - "/v2/api-docs/**"

debug: false
